# Generated by Django 4.1.5 on 2023-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_details',
            fields=[
                ('tid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=122, null=True)),
                ('temail', models.CharField(max_length=122, null=True)),
                ('tphone', models.CharField(max_length=122, null=True)),
                ('tdob', models.DateField(null=True)),
                ('tadd', models.TextField()),
                ('tsscs', models.CharField(max_length=122, null=True)),
                ('tsscp', models.CharField(max_length=122, null=True)),
                ('thscs', models.CharField(max_length=122, null=True)),
                ('thscp', models.CharField(max_length=122, null=True)),
                ('tgp', models.CharField(max_length=122, null=True)),
                ('tgc', models.CharField(max_length=122, null=True)),
                ('tpgp', models.CharField(max_length=122, null=True)),
                ('tpgc', models.CharField(max_length=122, null=True)),
                ('tge', models.CharField(max_length=122, null=True)),
                ('teq', models.CharField(max_length=122, null=True)),
                ('teqy', models.CharField(max_length=122, null=True)),
                ('teacher_service', models.CharField(max_length=122, null=True)),
                ('join_date', models.DateField(null=True)),
                ('teacher_salary', models.CharField(max_length=122, null=True)),
                ('teacher_exp', models.CharField(max_length=122, null=True)),
                ('field_name', models.FileField(blank='True', upload_to='media')),
            ],
        ),
    ]
