# Generated by Django 4.1.5 on 2023-03-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teacher_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_details',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
